### ISSUE TITLE
Add an open source license

### ISSUE THREAD

**Issue by SantanaSP** [SparkNFT/SparkLink#152]
## Summary

We need to add an open source license for this repository, and discuss everything about the license - include license changing procedure - before it gets added.

## Expected Behaviour

Add an opensource license & the standard procedure of chaing license.

## Roadmap

- [ ] Discuss about the license.
- [ ] Discuss the procedure of changing license.
- [ ] Add An opensource license. (Maintainer only)

Discussion will open by maintainers, and any developer is encouraged to engage in it.

**Comment by Erreth-Akbe** [comment]
I reaserched some project in Web 3.0 area. Most of them are using GPL license for their project.
[go-ethereum License](https://github.com/ethereum/go-ethereum/blob/master/COPYING)
[Mask Book License](https://github.com/DimensionDev/Maskbook/blob/develop/LICENSE)
[Uniswap protocal License](https://github.com/Uniswap/v2-core/blob/master/LICENSE)
Solana is using Apache License:
[Solana License](https://github.com/solana-labs/solana/blob/master/LICENSE)
Due to our project is similar to Uniswap protocal and some other Dapp, we are more decentralize than some POS or POH block chain, maybe GPL is a good choice.

**Comment by SantanaSP** [comment]
> I reaserched some project in Web 3.0 area. Most of them are using GPL license for their project. [go-ethereum License](https://github.com/ethereum/go-ethereum/blob/master/COPYING) [Mask Book License](https://github.com/DimensionDev/Maskbook/blob/develop/LICENSE) [Uniswap protocal License](https://github.com/Uniswap/v2-core/blob/master/LICENSE) Solana is using Apache License: [Solana License](https://github.com/solana-labs/solana/blob/master/LICENSE) Due to our project is similar to Uniswap protocal and some other Dapp, we are more decentralize than some POS or POH block chain, maybe GPL is a good choice.

I agree with you. To other individual contributors, please give a 👍to this comment if you agree to use GPL, or give a 👎if you prefer another license, so that maintainers could know your tendency. Since this project is formerly coded under SparkNFT team, the maintainer would decide which license to use as a consequence.

This comment will hang for at least 48 hours before the license is decided.
