### ISSUE TITLE
Customer need Polygon version contract to be used in SparkLink App.

### ISSUE THREAD

**Issue by Erreth-Akbe** [SparkNFT/SparkLink#168]
## Summary

Customer need Polygon version contract to be used in front end.

## Expected Behaviour
- [x] Our app should connects Polygon NetWork.
- [ ] Our app should support user publish NFT at Polygon Network.
- [ ] Our app should support user check their SparkLink NFT at Polygon Network.
- [ ] Our app should support user check share link form fron a SparkLink NFT at Polygon Network.
- [ ] (optional: When they have not connected their wallet maybe also need to display them the cover page and description by using http provider)
- [ ] (delete rinkeby support at formal production)
## Solution

Using production server whitch has been deployed at [server.sparklink.io](https://server.sparklink.io).
Using Polygon smart contract which has been deployed at [SparkLink Smart Contract](https://polygonscan.com/address/0xb83A6A35F1468BEA014e6Aa014300128D34ee433)
Contract Address: 0xb83A6A35F1468BEA014e6Aa014300128D34ee433
### Alternative

None.

## Additional context
A more reliable polygon rpc server:
https://rpc-mainnet.maticvigil.com
For more detail:
[Server Doc](https://github.com/SparkNFT/server/blob/develop/doc/api.apib)
[Contract Doc](https://github.com/SparkNFT/SparkLinkSmartContract)

## Roadmap

refactor branch.

**Comment by SantanaSP** [comment]
I'll take over this.
