### ISSUE TITLE
The community needs a bot that can verify if a user owns an NFT belongs to an issue.

### ISSUE THREAD

**Issue by Erreth-Akbe** [SparkNFT/SparkLink#186]
## Summary
The community hopes to use a published NFT tree structure as a membership card to enter a private group.

## Expected Behaviour

We need to make a telegram and discord bot which supports the following functions:
- [ ] First of all, the bot needs to have a core module that can be called by the telegram bot component and the discord bot component. The APIs of these two platforms are different, and the corresponding scope of what they can do is also different. For example, discord can send messages that are visible to a single person. Telegram can't do it. But in terms of bot function, discord and telegram should be the same.
- [ ] The first step is for the administrator to pull the bot into the group and bind an NFT issue. That is, the administrator enters the command /start to the bot, and the bot asks the administrator to enter any NFT ID corresponding to the issue.
- [ ] Then a new person enters the group, and the bot will first ask him to reply with a number, which is one of the NFT IDs he holds.
- [ ] It will then give him a browser URL, which he needs to open with a wallet or a browser connected to metamask, and sign it. The bot will check whether the signed address owns the NFT and the NFT is under the issue set by the administrator. After completion, the bot will not kick the person and delete the verification message. If the verification is not completed, and the timeout expires, the bot will kick him and delete the message.
- [ ] In this process, we need to consider the situation that some users are kicked out because they are not familiar with the product, or their operation is too slow. Therefore, part of the operation process may need further discussion, but we will do a demo according to this first, and consider how to modify it after testing and use.

## Solution

Need to be filled.

### Alternative

The community using collab.land bot now.

## Additional context

In the next step this boot should have ability to access sparklink server database.

## Roadmap

Refactor branch.
