### ISSUE TITLE
The spark page needs to display everything when the user is not connected to the wallet, and prompt the user to connect the wallet when the user clicks the mint button.

### ISSUE THREAD

**Issue by Erreth-Akbe** [SparkNFT/SparkLink#187]
## Summary

The spark page needs to display everything when the user is not connected to the wallet, and prompt the user to connect the wallet when the user clicks the mint button.

## Expected Behaviour

The spark page should display collection name, image and other information when the users opened the page without connected with their wallet.

## Solution
There are two types of functions when calling contract functions on Ethereum. One type of function is the function of view or pure. This function does not modify the information on the chain, but only reads some information on the chain at most. For example tokenURI(NFTID).
- [ ] That is, these functions do not need to be called from providers provided by metamask or other wallets. ethers.js supports the provider type of infura provider or http provider to call a read-only function. I'm not really sure that web3.js also supports such operations. If it is not supported, it may need to be refactored, but it should be impossible not to support it.
- [ ] The second problem is that, first of all, the rpc server may not support us to concurrently request a large number of tokenURI requests in a short time. For example, the rpc server of the eth mainnet and the RPC server of polygon will intercept such requests, but the RPC server of BSC is relatively forgiving. 
- [ ] For the eth mainnet and polygon mainnet, we can obtain an http rpc server by deploying a quick noede or purchasing infura's commercial services, and we can directly use infura's free services at this stage.
- [ ] But BSC may officially provide such free infura services. Research is required to determine.
- [ ] It is necessary to provide a pop-up window after the user is not connected to the wallet, but clicks the mint button, prompting the user to connect the wallet. Considering that users don't even know what a wallet is, maybe this place needs to provide a link to the wiki for users to learn.

### Alternative

Do not have.

## Additional context

Null.

## Roadmap

Refactor branch.

**Comment by SantanaSP** [comment]
Do not abuse task list please. In my opinion normal paragraphs are more suitable for the "solution" section.

**Comment by SantanaSP** [comment]
This issue will finally be traced in #188. The issue will be closed but any discussion related to this issue is still welcomed.
