### ISSUE TITLE
Customers need a mobile version publishing page

### ISSUE THREAD

**Issue by SantanaSP** [SparkNFT/SparkLink#85]
## Summary

For path `/publish` customers need a mobile version publishing page so that they can publish their art in their phone. Remember to reovle this issue, the customers should be able to upload their files using mobile device.

## Roadmap

- [X] [UI/UX design](https://www.figma.com/file/aOzhPxHjypqHt0v7yTXlGa/sparklink?node-id=981%3A1681)
- [x] Coding

## Validation

- [x] As a customer, I can link my wallet, upload file and approve the transaction when I use mobile device.
- [x] Use the `Dialog` component in the components folder to display the processing information.

**Comment by Geoffreyyy** [comment]
mobile version publishing page is done, check on figma pls

**Comment by Geoffreyyy** [comment]
> mobile version publishing page is done, check on figma pls

in the red window

**Comment by SantanaSP** [comment]
I’ll take It.
