### ISSUE TITLE
Customer need a Spark Page in PC client.

### ISSUE THREAD

**Issue by Erreth-Akbe** [SparkNFT/SparkLink#87]
## Summary

For path `/art/NFTID` page, now customer and owner can access same page and display different componet.
But we should split this two pages for customer and owner. 
`/art` for owner, it will has download, recieve income model.

`/spark` for customer and this page's url will also be in `Link Share` and `Poster Share`. It will has Mint and Download model.

## Roadmap

- [x] [Art page UI/UX design] (https://www.figma.com/file/aOzhPxHjypqHt0v7yTXlGa/sparklink?node-id=684%3A1375)
- [x] [Spark page UI/UX design] (https://www.figma.com/file/aOzhPxHjypqHt0v7yTXlGa/sparklink?node-id=844%3A1375)
- [ ] [Art page] Coding
- [ ] [Spark page] Coding

## Validation

- [ ] As a customer, I can Mint a child node NFT at Spark Page, the jump to the art page for my new NFT node.
- [ ] Use the `Dialog` component in the components folder to display the processing information.

**Comment by codeAtNow** [comment]
I will deal with it

**Comment by SantanaSP** [comment]
Fine, nobody found that we didn't have prototype between spark page and art page?

**Comment by codeAtNow** [comment]
I push a new PR #93

**Comment by SantanaSP** [comment]
Don't write down unrelated things here. Notify me using discord.

**Comment by SantanaSP** [comment]
Okay, I'll check it.

**Comment by SantanaSP** [comment]
What about adding a context switching button so that visitor can easily change their view between art view and spark view? Currently if a customer visit the art page through wrong link (shared by owner by just copying and pasting the url in the address bar) he may feel odd because we encapsulate the views for him, i.e., he is in owner view, but he doesn't have an idea of it. So if we just add such a context switching button, he can easily figure out he's in owner view, and switch to customer view to mint NFT if he like.

**Comment by SantanaSP** [comment]
@Erreth-Akbe

**Comment by Geoffreyyy** [comment]
> 

I think its not a priority if other stuffs not done yet:)
the  context switching button

**Comment by Erreth-Akbe** [comment]
yes, at this time it is not a first priority thing. We can design this featrue now.

**Comment by SantanaSP** [comment]
Fine, I'll leave a TODO mark and deal with it after we complete the current epic.

**Comment by Erreth-Akbe** [comment]
The final page doesn't match the design draft. Below is design draft.

![image](https://user-images.githubusercontent.com/104019956/166727889-96bb675c-660d-4a41-8bae-b8b929039cd9.png)

Below is PR version.

![image](https://user-images.githubusercontent.com/104019956/166727962-3056242f-eb05-4ed3-9608-a367fec13645.png)

Please check whether **all of** your pages match the design draft.
@codeAtNow

**Comment by SantanaSP** [comment]
There are obvious flaws in PR #100 , so I'll reopen this issue.

**Comment by SantanaSP** [comment]
I’ll take over this.

**Comment by codeAtNow** [comment]
> I’ll take over this.

This Issue still have ant work to do?
