### ISSUE TITLE
Customer need a Spark Page in mobile client.

### ISSUE THREAD

**Issue by Erreth-Akbe** [SparkNFT/SparkLink#88]
## Summary

For path `/art/NFTID` page, now costomer and owner can access same page and display different componet.
But we should split this two pages for customer and owner. 
`/art` for owner, it will has download, recieve income model.

`/spark` for customer and this page's url will also be in `Link Share` and `Poster Share`. It will has Mint and Download model.

## Roadmap

- [x] [Art page UI/UX design](https://www.figma.com/file/aOzhPxHjypqHt0v7yTXlGa/sparklink?node-id=1189%3A3018)
- [x] [Spark page UI/UX design](https://www.figma.com/file/aOzhPxHjypqHt0v7yTXlGa/sparklink?node-id=1412%3A1879)
- [ ] [Art page] Coding
- [ ] [Spark page] Coding

## Validation

- [ ] As a customer, I can Mint a child node NFT at Spark Page, the jump to the art page for my new NFT node.
- [ ] Use the `Dialog` component in the components folder to display the processing information.

**Comment by Geoffreyyy** [comment]
under designing.

**Comment by Geoffreyyy** [comment]
done, pls check pages new :https://www.figma.com/file/aOzhPxHjypqHt0v7yTXlGa/sparklink?node-id=1184%3A1568

**Comment by SantanaSP** [comment]
I'll take over this.
